import { Inter } from "next/font/google";
import "./globals.css";
import TransitionProvider from "@/components/transitionProvider";
import { ThemeProvider } from "next-themes";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ndifreke Portfolio App",
  description: "Generated by create next app",
};

export default function RootLayout({ children}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class">
          <TransitionProvider>
          {children}
        </TransitionProvider> 
        </ThemeProvider>
        
      </body>
    </html>
  );
}
